### ISSUE TITLE
testing with curl, issues

### ISSUE THREAD

**Issue by Grusinator** [lmcgartland/graphene-file-upload#7]
i added the package to my setup, and tried to test it using curl from the example of https://github.com/jaydenseric/graphql-multipart-request-spec, i guess it should be working. modified a bit.

upload mutation:

```
class UploadMutation(graphene.Mutation):
    class Arguments:
        file = Upload(required=True)

    success = graphene.Boolean()

    def mutate(self, info, file, **kwargs):
        # file parameter is key to uploaded file in FILES from context
        uploaded_file = info.context.FILES.get(file)
        # do something with your file
        return UploadMutation(success=True)

class Mutation(graphene.ObjectType):
    upload_mutation = UploadMutation.Field()
```

i did the `ModifiedGraphQLView` modification as well.

when i run the current command:

```
curl http://localhost:8000/graphql -F operations='{ "query": "mutation ($file: Upload!) {
 uploadMutation(file: $file) { id } }", "variables": { "file": null } }' -F map='{ "0": ["variables.file"] }' -F 0=@"C:\
Users\William S. Hansen\Documents\upload.txt"
```

i only changed the mutation name, the uri, and the path to the file.

i get the following error:
```
Internal Server Error: /graphql
Traceback (most recent call last):
  File "C:\Users\William S. Hansen\source\repos\web\PersonalDataApi\PersonalDataApi\env\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\William S. Hansen\source\repos\web\PersonalDataApi\PersonalDataApi\env\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\William S. Hansen\source\repos\web\PersonalDataApi\PersonalDataApi\env\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\William S. Hansen\source\repos\web\PersonalDataApi\PersonalDataApi\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\William S. Hansen\source\repos\web\PersonalDataApi\PersonalDataApi\env\lib\site-packages\django\utils\decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\William S. Hansen\source\repos\web\PersonalDataApi\PersonalDataApi\env\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\William S. Hansen\source\repos\web\PersonalDataApi\PersonalDataApi\env\lib\site-packages\django\utils\decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\William S. Hansen\source\repos\web\PersonalDataApi\PersonalDataApi\env\lib\site-packages\graphene_django\views.py", line 119, in dispatch
    request, data, show_graphiql)
  File "C:\Users\William S. Hansen\source\repos\web\PersonalDataApi\PersonalDataApi\env\lib\site-packages\graphene_django\views.py", line 149, in get_response
    request, data)
  File "C:\Users\William S. Hansen\source\repos\web\PersonalDataApi\PersonalDataApi\env\lib\site-packages\graphene_file_upload\__init__.py", line 47, in get_graphql_params
    raise e
  File "C:\Users\William S. Hansen\source\repos\web\PersonalDataApi\PersonalDataApi\env\lib\site-packages\graphene_file_upload\__init__.py", line 30, in get_graphql_params
    operations = json.loads(operations)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
```

is it the request that is wrong, or what am i not getting?

what is it with those double quotes? 

it seems like the curl command is also complaining a bit, from the terminal:

```
curl: (6) Could not resolve host: ($file
curl: (6) Could not resolve host: Upload!)
curl: (3) [globbing] unmatched brace in column 1
curl: (6) Could not resolve host: uploadMutation(file
curl: (6) Could not resolve host: $file)
curl: (3) [globbing] unmatched brace in column 1
curl: (6) Could not resolve host: id
curl: (3) [globbing] unmatched close brace/bracket in column 1
curl: (3) [globbing] unmatched close brace/bracket in column 1
```

thanks :)

**Comment by Grusinator** [comment]
Thanks for your suggestion. 

unfortunately none of it seemed to be the cause. i tried to run it on my Ubuntu machine instead with the following command:

(i changed the mutation name to singleUpload)

```
 curl localhost:8000/graphql \
   -F operations='{ "query": "mutation ($file: Upload!) { singleUpload(file: $file) { success } }", "variables": { "file": null } }' \
  -F map='{ "0": ["variables.file"] }' \
  -F 0=@upload.txt
```
which returns:
```
{"errors":[{"message":"Must provide query string."}]}
```

i also tried a bit with insomnia, but i don't manage to understand how to fill in the `variables` without it complaining. 
fx:
```
{
    "file" : null
}
```
gives an insomnia error which says: 
Type "Upload!" is non-nullable and cannot be null

the header is like 
map      {"0":["variables.file"]}
0           File 

where file is the built in file selection tool.

do you know what i am doing wrong?

could you maybe explain me, or refer me to something that explains me the logic behind the "map" and "0" keys in the header?

**Comment by davidroeca** [comment]
I'm not sure what's going wrong, and it's hard to know what's going wrong without seeing code. What I can say for now is to make sure there is no code that can possibly be running with the standard `GraphQLView` and instead make sure that you're only importing the `ModifiedGraphQLView`, like in [the readme](https://github.com/lmcgartland/graphene-file-upload#usage).

Motivations behind the "map", etc are defined in https://github.com/jaydenseric/graphql-multipart-request-spec#multipart-form-field-structure

Since Insomnia isn't a GraphQL client for file upload as per the multipart request spec, you'll have to use the basic file upload request option and manually enter the values.

**Comment by Grusinator** [comment]
I made it work. Thanks a lot. I was using the GraphQL, not using the "Multipart form" in insomnia.

**Comment by weilu** [comment]
I've been getting `{"errors":[{"message":"Must provide query string."}]}` for the last 2 hours and have been banging my head over this. Turned out it was because I didn't replace `GraphQLView.as_view` with `FileUploadGraphQLView.as_view` in `urls.py` – in case this may help someone else out there.
